name: Mainnet deployment

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: false
      REACT_APP_NEAR_ORACLE_CONTRACT_ID: v1.fluxoracle.near
      REACT_APP_NEAR_NULL_CONTRACT: null_address.near
      REACT_APP_NEAR_NETWORK: mainnet
      REACT_APP_API_URL: https://mainnet-explorer-api.flux.xyz/graphql

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: cp .env.example .env
    - run: echo "REACT_APP_NEAR_ORACLE_CONTRACT_ID = $REACT_APP_NEAR_ORACLE_CONTRACT_ID" >> .env
    - run: echo "REACT_APP_NEAR_NULL_CONTRACT = $REACT_APP_NEAR_NULL_CONTRACT" >> .env
    - run: echo "REACT_APP_NEAR_NETWORK = $REACT_APP_NEAR_NETWORK" >> .env
    - run: echo "REACT_APP_API_URL = $REACT_APP_API_URL" >> .env
    - run: npm run build --if-present
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'   # optional: defaults to us-east-1
        SOURCE_DIR: 'build'      # optional: defaults to entire repository


