name: Mainnet deployment

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: false
      REACT_APP_NEAR_ORACLE_CONTRACT_ID: 09.oracle.flux-dev

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: cp .env.example .env
    - run: echo "REACT_APP_NEAR_ORACLE_CONTRACT_ID = $REACT_APP_NEAR_ORACLE_CONTRACT_ID" >> .env
    - run: npm run build --if-present
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build


